
name: .NET Core 

on:
  push:
    branches: [ master ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      AZURE_WEBAPP_NAME: nextech-hacker-news                    # set this to your application's name
      AZURE_WEBAPP_PACKAGE_PATH: 'deployments'                  # set this to the path to your web app project, defaults to the repository root
      Solution_Name: hacker-news.csproj                         # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path: /test                                  # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.
      DOTNET_VERSION: '3.1.301'                                 # set this to the dot net version to use
   
       
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Build with dotnet
      run: dotnet build hacker-news/hacker-news.csproj  --configuration Release
    - name: Test with dotnet
      run: dotnet test test-hacker-news/test-hacker-news.csproj --configuration Release
    - name: dotnet publish
      run: |
        dotnet publish hacker-news -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}  # Define secret variable in repository settings as per action documentation
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
