
name: .NET Core 

on:
  push:
    branches: [ master ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: hacker-news.csproj                         # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path: /test                                  # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.
      Wap_Project_Directory: your-wap-project-directory-name    # Replace with the Wap project directory relative to the solution, i.e. MyWpfApp.Package.
      Wap_Project_Path: your-wap-project-path                   # Replace with the path to your Wap project, i.e. MyWpf.App.Package\MyWpfApp.Package.wapproj.

   
       
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build with dotnet
      run: dotnet build hacker-news/hacker-news.csproj  --configuration Release
    - name: Test with dotnet
      run: dotnet test test-hacker-news/test-hacker-news.csproj --configuration Release
    - name: dotnet publish
      run: |
        dotnet publish hacker-news -c Release -o deployments
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: nextech-hacker-news # Replace with your app name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}  # Define secret variable in repository settings as per action documentation
        package: deployments
